name: Compressed Size

on: [pull_request]

jobs:
  compressed-size:
    name: Compressed Size
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js latest
        uses: actions/setup-node@v3
        with:
          node-version: "*"
          cache: "yarn"
      - uses: preactjs/compressed-size-action@v2
        with:
          build-script: "compressed-size"
          pattern: "./package/*/lib/**"
          exclude: ""
